added hyperedge option and clusters (#926)
eclipse/elk pull request #927
Opened 2023-05-19 14:45 UTC by lindhuber

Libavoid: Added hyperedge option and clusters #926

Clusters can now be modelled as hierarchical nodes (with certain restrictions).
Hyperedges have to be handled by the libavoid process itself, but an option is needed to "activate" them.

Signed-off-by: Daniel Lindhuber <daniel.lindhuber@jku.at>

2023-06-01 11:06 UTC, soerendomroes requested changes
The changes look good, I have, however, not tested this feature. Could you add a basic libavoid graph to the [elk-models repository](https://github.com/eclipse/elk-models/tree/master) after this PR is merged?

2023-06-01 11:06 UTC, soerendomroes commented on plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/Libavoid.melk
> +                 2023 Primetals Technologies Austria GmbH
Can you add the organization to the line above?
I.e.: 2016, 2023 Kiel University, Primetals Technologies Austria GmbH and others.

2023-06-01 11:06 UTC, soerendomroes commented on plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidServerCommunicator.java
> + *               2023 Primetals Technologies Austria GmbH
See comment above.

2023-06-01 11:06 UTC, soerendomroes commented on plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidServerCommunicator.java
> +
Unnecessary whitespace

2023-06-01 11:06 UTC, soerendomroes commented on plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidServerCommunicator.java
> +    private boolean isCluster(final ElkNode node) {
Please add Javadoc.

2023-06-01 11:06 UTC, soerendomroes commented on plugins/org.eclipse.elk.alg.libavoid/src/org/eclipse/elk/alg/libavoid/LibavoidServerCommunicator.java
> +    private void transformCluster(final ElkNode node) {
Please add Javadoc

2023-06-15 09:52 UTC, soerendomroes commented
@lindhuber Could you also resolve the conflicts? It seem that by adding the omitNodeMicroLayout option, your two new options cannot be automatically merged.

2023-06-15 14:15 UTC, lindhuber commented
@soerendomroes Should be done now, thank you for your patience. :D

2023-06-26 09:41 UTC, soerendomroes approved these changes

2023-06-26 09:41 UTC, merged