Radial layout: center on root option
eclipse/elk pull request #941
Opened 2023-07-03 06:49 UTC by Eddykasp

This option allows a radial to be automatically centered on its root node. This is achieved by increasing the overall size of the layout and shifting all nodes accordingly.

2023-07-03 13:10 UTC, soerendomroes requested changes
Have you considered adding a test for this?

2023-07-03 13:10 UTC, soerendomroes commented on plugins/org.eclipse.elk.alg.radial/src/org/eclipse/elk/alg/radial/intermediate/CalculateGraphSize.java
> +            double rootX = root.getX() + root.getWidth()/2 + (rootMargins.left + rootMargins.right)/2 - offset.x;
Maybe add a small explanation for this formula

2023-07-03 13:10 UTC, soerendomroes commented on plugins/org.eclipse.elk.alg.radial/src/org/eclipse/elk/alg/radial/intermediate/CalculateGraphSize.java
> +
Additional whitespace

2023-07-03 13:16 UTC, Eddykasp commented
> Have you considered adding a test for this?

I thought you might ask that. I'll add that and address the other things as well.

2023-07-04 14:34 UTC, soerendomroes requested changes

2023-07-04 14:34 UTC, soerendomroes commented on test/org.eclipse.elk.alg.radial.test/.project
> +	<name>org.eclipse.elk.alg.disco.test</name>
Why is this project called disco.test?

2023-07-04 14:34 UTC, soerendomroes commented on test/org.eclipse.elk.alg.radial.test/META-INF/MANIFEST.MF
> +Bundle-Name: ELK Layout DisCo Tests
Name

2023-07-04 14:34 UTC, soerendomroes commented on test/org.eclipse.elk.alg.radial.test/build.properties
> +# Copyright (c) 2019 Kiel University and others.
Wrong year

2023-07-04 14:34 UTC, soerendomroes commented on test/org.eclipse.elk.alg.radial.test/pom.xml
> +  Copyright (c) 2017 Kiel University and others.
Wrong year

2023-07-04 14:56 UTC, soerendomroes approved these changes

2023-07-06 09:21 UTC, merged